@startuml
title Диаграмма контекста текущей системы "Тёплый дом"

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы 'Тёплый дом'")
Person(connectionEngineer, "Специалист", "Специалист по подключению системы отопления")

System(warmhouseSystem, "Система 'Тёплый дом'", "Система позволяет управлять системой отопления и снимать показания с датчиков")

System_Ext(heatingSystem1, "Система1", "Система отопления", "Использует REST, данные в формате JSON")
System_Ext(heatingSystem2, "Система2", "Система отопления", "Использует REST, данные в формате JSON")
System_Ext(heatingSystemN, "СистемаN", "Система отопления", "Использует REST, данные в формате JSON")

Rel(user, warmhouseSystem, "Использует систему")
Rel(connectionEngineer, warmhouseSystem, "Подключает системы отопления к системе, регистрирует датчики в системе, выполняет настройку соединения")
Rel(warmhouseSystem, heatingSystem1, "Передаёт команды, запрашивает показания.")
Rel(warmhouseSystem, heatingSystem2, "Передаёт команды, запрашивает показания.")
Rel(warmhouseSystem, heatingSystemN, "Передаёт команды, запрашивает показания.")

@enduml